version: '3'
services:
  consul:
    image: consul:latest
    command: agent -dev -client=0.0.0.0 -bind=0.0.0.0
    ports:
      - 8500:8500
  poc-consul-lock:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: nokamoto13/poc-consul-lock:latest
    environment:
      - CONSUL_HTTP_ADDR=consul:8500
    depends_on:
      - consul
